import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-zinc-900 w-full flex justify-center items-center">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-lg flex justify-center items-center w-full`}
      >
        {children}
      </body>
    </html>
  );
}
