import "./globals.css";
import DashFooter from "@/components/DashFooter"
import DashHeader from "@/components/DashHeader"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-zinc-900 w-full flex justify-center items-center">
      <body
        className={`antialiased max-w-lg bg-[var(--background)] flex justify-center items-center w-full min-h-[100dvh] relative`}
      >
        <DashHeader />
        {children}
        <DashFooter />
      </body>
    </html>
  );
}
