import "@/app/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function SignInLayout({ children }) {
  return (
    <html lang="en" className="bg-zinc-900 w-full flex justify-center items-center">
      <body
        className={`antialiased max-w-lg flex justify-center items-center w-full min-h-[100dvh]`}
      >
        {children}
      </body>
    </html>
  );
}